name: Build

on:
  push:
    #paths-ignore:
      #- ".github/workflows/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify Format
        run: dotnet format --verify-no-changes

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --logger trx
